spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: admin
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
